// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#include "hal.h"
#include "mongoose/mongoose_glue.h"

static struct files s_files[] = {
  {100, "One.txt"},
  {180, "Two.txt"},
  {200, "Three.txt"},
  {40, "Four.txt"},
};
bool my_get_files(struct files *data, size_t i) {
  size_t array_size = sizeof(s_files) / sizeof(s_files[0]);
  if (i >= array_size) return false;
  *data = s_files[i];  // Sync with your device
  return true;
}
void my_set_files(struct files *data, size_t i) {
  size_t array_size = sizeof(s_files) / sizeof(s_files[0]);
  if (i < array_size) s_files[i] = *data; // Sync with your device
}

bool my_check_delete(void) {
  return false;
}
void my_start_delete(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));

}

size_t my_file_read_upload(char *path, size_t offset, void *buf, size_t len) {
  MG_INFO(("\npath: %s, ofs: %lu, buf: %p, len: %lu", path, offset, buf, len));
  if (offset != 0)
	  return 0;
  snprintf((char *)buf,  len, "<html><body><H1>Stub file</H1><H2>%s</H2></body></html>", path);
  return strlen(buf);
}
bool my_file_write_upload(char *path, size_t offset, void *buf, size_t len) {
  MG_INFO(("\npath: %s, ofs: %lu, buf: %p, len: %lu", path, offset, buf, len));
  return true;
}


int main(void) {
  // Cross-platform hardware init
  hal_init();
  MG_INFO(("HAL initialised, starting firmware..."));

  // This blocks forever. Call it at the end of main(), or in a
  // separate RTOS task. Give that task 8k stack space.
  mongoose_init();

  mongoose_set_http_handlers("files", my_get_files, my_set_files);
  mongoose_set_http_handlers("delete", my_check_delete, my_start_delete);
  mongoose_set_http_handlers("upload", my_file_read_upload, my_file_write_upload);

  for (;;) {
    mongoose_poll();
  }

  return 0;
}
