// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static uint64_t s_action_timeout_delete;  // Time when delete ends
bool glue_check_delete(void) {
  return s_action_timeout_delete > mg_now(); // Return true if delete is in progress
}
void glue_start_delete(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_delete = mg_now() + 1000; // Start delete, finish after 1 second
}

static struct files s_files[] = {
  {42, "foo.txt"},
  {42, "foo.txt"},
  {42, "foo.txt"},
};
bool glue_get_files(struct files *data, size_t i) {
  size_t array_size = sizeof(s_files) / sizeof(s_files[0]);
  if (i >= array_size) return false;
  *data = s_files[i];  // Sync with your device
  return true;
}
void glue_set_files(struct files *data, size_t i) {
  size_t array_size = sizeof(s_files) / sizeof(s_files[0]);
  if (i < array_size) s_files[i] = *data; // Sync with your device
}
size_t glue_file_read_upload(char *path, size_t offset, void *buf, size_t len) {
  MG_INFO(("path: %s, ofs: %lu, buf: %p, len: %lu", path, offset, buf, len));
  return 0;
}
bool glue_file_write_upload(char *path, size_t offset, void *buf, size_t len) {
  MG_INFO(("path: %s, ofs: %lu, buf: %p, len: %lu", path, offset, buf, len));
  return true;
}
