// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#include "hal.h"
#include "mongoose/mongoose_glue.h"
#include <stdio.h>
#include <string.h>
#include <dirent.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>

const char*   TARGET_FOLDER = "/tmp";
#define FN_LEN 256


bool my_get_files(struct files *data, size_t i) {
	DIR*           fd;
	int fildes;
	struct dirent* in_file;
	size_t count =0;
	bool found = false;
    struct stat buffer;
    int         status;
    char fullname[FN_LEN];

	fd = opendir(TARGET_FOLDER);
	if (fd == NULL)
	{
		printf("Error : Failed to open target directory - %s\n", strerror(errno));
		return false;
	}

	while ((in_file = readdir(fd))){
		if (DT_REG == in_file->d_type){
			printf("%s is file\n", in_file->d_name);

			if (count == i){
				strcpy(data->name, in_file->d_name);
				data->size=0;
				snprintf(fullname, FN_LEN, "%s/%s", TARGET_FOLDER,  in_file->d_name);
				fildes = open(fullname, O_RDWR);
				if (fildes > 0){
					status = fstat(fildes, &buffer);
					if (status >= 0)
						data->size=buffer.st_size;
					else
						printf("ERROR: stat %s failed with code %d\n", fullname, status);
					close (fildes);
				} else {
					printf("ERROR: open %s failed with code %d\n", fullname, fildes);
				}
				found = true;
				break;
			}
			count ++;
		}
	}

	/* Close the directory */
	closedir(fd);

	return found;
}


void my_set_files(struct files *data, size_t i) {
	DIR*           fd;
	struct dirent* in_file;
	size_t count =0;

    char oldname[FN_LEN];
    char newname[FN_LEN];

    snprintf(newname, FN_LEN, "%s/%s", TARGET_FOLDER,  data->name);

	fd = opendir(TARGET_FOLDER);
	if (fd == NULL)
	{
		printf("Error : Failed to open target directory - %s\n", strerror(errno));
		return ;
	}

	while ((in_file = readdir(fd))){
		if (DT_REG == in_file->d_type){
			//printf("%s is file\n", in_file->d_name);

			if (count == i){
				strcpy(data->name, in_file->d_name);
				data->size=0;
				snprintf(oldname, FN_LEN, "%s/%s", TARGET_FOLDER,  in_file->d_name);

				int  res = rename(oldname, newname);

			    if (!res) {
			        printf("File name changed successfully\n");
			    }
			    else {
			        printf("File rename failed\n");
			    }

				break;
			}
			count ++;
		}
	}

	/* Close the directory */
	closedir(fd);
}



bool my_check_delete(void) {
  return false;
}
void my_start_delete(struct mg_str params) {
	char fullname[FN_LEN];
	//MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));

	snprintf(fullname, FN_LEN, "%s/%.*s", TARGET_FOLDER,  (int)params.len, params.buf);
	remove(fullname);
}

size_t my_file_read_upload(char *path, size_t offset, void *buf, size_t len) {
	FILE *fp ;
	char fullname[FN_LEN];
	size_t res = 0;

	snprintf(fullname, FN_LEN, "%s/%s", TARGET_FOLDER,  path);

    fp = fopen(fullname, "rb");
    if (fp != NULL){
    	printf("Opened %s (offset %zu, len %zu)\n", fullname, offset, len);
    	if (offset > 0){
			 if( fseek(fp, offset, SEEK_SET) != 0){
				 printf("Error - failed to seek pos in %s\n", fullname);
				 fclose(fp);
				 return 0;
			 }
    	 }

		res  = fread(
				buf,
				1,
				len,
				fp
				);
		printf("read %zu\n", res);
    	fclose(fp);
    } else {
    	printf("Open for R failed\n");
    }

    return res;
}

bool my_file_write_upload(char *path, size_t offset, void *buf, size_t len) {
	FILE *fp ;
	char fullname[FN_LEN];
	size_t res = 0;

	snprintf(fullname, FN_LEN, "%s/%s", TARGET_FOLDER,  path);

	if (offset == 0)
		fp = fopen(fullname, "w");
	else
		fp = fopen(fullname, "a");

	if (fp != NULL){
		//printf("Opened %s (offset %zu, len %zu)\n", fullname, offset, len);
		res = fwrite(
				buf,
				1,
				len,
				fp
				);
		fclose(fp);
	} else  {
		printf("Open for W/A failed\n");
	}

	printf("Upload %s %zu (%zu) achieved %zu\n",  fullname,  len, offset, res);
	return (res == len);
}



int main(void) {
  // Cross-platform hardware init
  hal_init();
  MG_INFO(("HAL initialised, starting firmware..."));

  // This blocks forever. Call it at the end of main(), or in a
  // separate RTOS task. Give that task 8k stack space.
  mongoose_init();

  mongoose_set_http_handlers("files", my_get_files, my_set_files);
  mongoose_set_http_handlers("delete", my_check_delete, my_start_delete);
  mongoose_set_http_handlers("upload", my_file_read_upload, my_file_write_upload);

  for (;;) {
    mongoose_poll();
  }

  return 0;
}
